name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Pack NuGet package
        run: dotnet pack CADability/CADability.csproj -c Release -o ./nupkgs

      - name: List .nupkg files
        run: dir .\nupkgs

      - name: Validate NuGet packages
        run: |
          if (!(Test-Path "./nupkgs/*.nupkg")) {
            Write-Host "No .nupkg files found. Failing the workflow.";
            exit 1;
          }

      - name: Push to NuGet
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
